// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package pgsqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         int64
	Uid        pgtype.UUID
	Email      string
	Password   string
	FullName   string
	IsStaff    bool
	IsActive   bool
	LastLogin  pgtype.Timestamptz
	CreatedAt  time.Time
	ModifiedAt time.Time
}
